export const productosSeed = [
  {
    codigoInterno: 'GGM-001',
    codigoBarras: '7701234560012',
    nombre: 'Granola artesanal miel y nueces',
    descripcion: 'Bolsa 400g, horneada en casa',
    precioCompra: 9500,
    precioVenta: 15900,
    iva: 0,
    categoria: 'Desayuno',
    marca: 'Guapa Bakery',
    unidadMedida: 'unidad',
    existencias: 24,
    favoritoPos: true,
  },
  {
    codigoInterno: 'GGM-002',
    codigoBarras: '7701234560029',
    nombre: 'Leche de almendras sin azúcar',
    descripcion: 'Botella 1L',
    precioCompra: 6800,
    precioVenta: 11500,
    iva: 5,
    categoria: 'Bebidas vegetales',
    marca: 'PureNut',
    unidadMedida: 'unidad',
    existencias: 12,
    favoritoPos: true,
  },
  {
    codigoInterno: 'GGM-003',
    codigoBarras: '7701234560036',
    nombre: 'Mix de frutos secos premium',
    descripcion: 'Bolsa 250g',
    precioCompra: 12000,
    precioVenta: 19900,
    iva: 0,
    categoria: 'Snacks',
    marca: 'Guapa Selección',
    unidadMedida: 'unidad',
    existencias: 3,
    favoritoPos: false,
  },
  {
    codigoInterno: 'GGM-004',
    codigoBarras: '7701234560043',
    nombre: 'Miel orgánica de abeja',
    descripcion: 'Frasco 500g',
    precioCompra: 14000,
    precioVenta: 23500,
    iva: 0,
    categoria: 'Endulzantes',
    marca: 'Apiario Sabana',
    unidadMedida: 'unidad',
    existencias: 18,
    favoritoPos: false,
  },
  {
    codigoInterno: 'GGM-005',
    codigoBarras: '7701234560050',
    nombre: 'Kombucha jengibre y limón',
    descripcion: 'Botella 330ml',
    precioCompra: 4200,
    precioVenta: 8900,
    iva: 19,
    categoria: 'Bebidas fermentadas',
    marca: 'Viva Kombucha',
    unidadMedida: 'unidad',
    existencias: 0,
    favoritoPos: true,
  },
  {
    codigoInterno: 'GGM-006',
    codigoBarras: '7701234560067',
    nombre: 'Proteína vegetal de arveja',
    descripcion: 'Tarro 900g, sabor vainilla',
    precioCompra: 62000,
    precioVenta: 98000,
    iva: 19,
    categoria: 'Suplementos',
    marca: 'PlantFuel',
    unidadMedida: 'unidad',
    existencias: 7,
    favoritoPos: false,
  },
  {
    codigoInterno: 'GGM-007',
    codigoBarras: '7701234560074',
    nombre: 'Aceite de coco extra virgen',
    descripcion: 'Frasco 500ml',
    precioCompra: 15500,
    precioVenta: 26900,
    iva: 5,
    categoria: 'Despensa',
    marca: 'Guapa Selección',
    unidadMedida: 'unidad',
    existencias: 21,
    favoritoPos: false,
  },
];
